export enum ActionTypes {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  CLEAN_ERROR = "CLEAN_ERROR",

  CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL",
}
