export enum ActionTypes {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  CLEAN_ERROR = "CLEAN_ERROR",

  CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS",
  DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL",
  GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS",
  GET_BLOG_FAIL = "GET_BLOG_FAIL",
  GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS",
  GET_BLOGS_FAIL = "GET_BLOGS_FAIL",
  CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL",
  EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS",
  EDIT_BLOG_FAIL = "EDIT_BLOG_FAIL",
  CLEAN_BLOGS = "CLEAN_BLOGS",
  CLEAN_BLOG = "CLEAN_BLOG",

  CREATE_ARTICLE_SUCCESS = "CREATE__ARTICLE_SUCCESS",
  CREATE_ARTICLE_FAIL = "CREATE_ARTICLE_FAIL",
  DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS",
  DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL",
  EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS",
  EDIT_ARTICLE_FAIL = "EDIT_ARTICLE_FAIL",

  SET_BLOG_ERROR = "SET_BLOG_ERROR",

  SET_IS_LOADING = "SET_IS_LOADING"
}
